### ISSUE TITLE
Error using the latest build

### ISSUE THREAD

**Issue by rafalfaro18** [willhallonline/docker-wordpress-phpcs#1]
Hi, I'm getting this error:

**Fatal error: Uncaught PHP_CodeSniffer_Exception: Referenced sniff "PSR12.Keywords.ShortFormTypeKeywords" does not exist in /root/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167**

I'm using the latest build on docker hub.

**Comment by rafalfaro18** [comment]
I remember I used your docker image a few months ago and this error didn't appear.

**Comment by rafalfaro18** [comment]
I built an image using this Dockerfile and works without any problem.

~~~~
FROM willhallonline/phpcs:php-7.2


RUN git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git /root/wpcs


RUN phpcs --config-set installed_paths /root/wpcs
RUN phpcs --config-set default_standard WordPress

WORKDIR /app

CMD ["phpcs"]
CMD ["phpcbf"]
~~~~

**Comment by willhallonline** [comment]
OK... It is a because WordPress coding standards is now working with PHP_Codesniffer 3.x - I'll update the Dockerfile. Thanks a lot for letting me know and also being so descriptive. New version landing in about 10 minutes. :+1:

**Comment by rafalfaro18** [comment]
Thank you @willhallonline your docker image is awesome by the way.

**Comment by willhallonline** [comment]
Thanks. I have based the ```latest``` on alpine (as it is smaller) but all updated in Docker Hub now too.
